### ISSUE TITLE
Missing Repo and Failed Builds 

### ISSUE THREAD

**Issue by mikevocalz** [voxeet/voxeet-sdk-reactnative#151]
when adding "$ yarn add @dolbyio/react-native-iapi-sdk --save" to a project it doesn't exist, not even on NPM or yarn. The second install link: $ yarn add https://github.com/codlab/react-native-voxeet-sdk --save is pointing to an outdated repo. When added the build fails. The naming of the projects are different a some warnings are present in the build failed output. The documentation to add this to android and ios needs to be updated as well.

**Comment by elishaterada** [comment]
I've run into the same issue. I'm unable to install the React Native SDK.

**Comment by jchang0419** [comment]
Sorry for the confusion, but this project is still a work in progress and not meant to be used yet.
